### ISSUE TITLE
About AUC！

### ISSUE THREAD

**Issue by ZHEGG** [LMMMEng/LLD-MMRI-Dataset#1]
Hello! Thank you very much for your open-source dataset and code! While reading your paper, I became confused about how the AUC metric is calculated for multi-class tasks. I have generated an AUC curve for each class, resulting in a total of 7 AUC curves (since there are 7 classes). How should these 7 AUC curves be processed to obtain an overall AUC? I would like to know your specific method for calculating the AUC. Thank you!

**Comment by LMMMEng** [comment]
Hi,
We employ a one-hot embedding to transform the label, and subsequently compute the AUC using the corresponding score.

**Comment by LMMMEng** [comment]
Feel free to reopen the issue if you have follow-up questions.
