### ISSUE TITLE
MedSAM for liver tumor mask

### ISSUE THREAD

**Issue by JunMa11** [LMMMEng/LLD-MMRI-Dataset#2]
Hi @LMMMEng ,

Thank you so much for making the invaluable dataset to the community. 

I'd like to share the MedSAM-generated tumor segmentation masks, which could be useful for segmentation related research topics

- tumor mask: https://drive.google.com/file/d/1spvmPVQuFT6avhGTQ3gYHjeBDGHI_AN2/view?usp=sharing
- preprocessing code: https://github.com/bowang-lab/MedSAM/blob/LiteMedSAM/LLD_MMRI_step0_data_preprocess.py
- inference code: https://github.com/bowang-lab/MedSAM/blob/LiteMedSAM/LLD_MMRI_step1_LiteMedSAM_Infer_MR_LiverCancer.py

Please feel free to let me know if you have any questions. 

Best,
Jun

**Comment by LMMMEng** [comment]
Dear Dr. Ma,

We greatly appreciate the updated information you have provided, which has been promptly added to our homepage. Thank you so much again!

Best,

LLD-MMRI Team
