### ISSUE TITLE
Can direction parameters for each raw image be added to the provided JSON files in the dataset?

### ISSUE THREAD

**Issue by QianMuXiao** [LMMMEng/LLD-MMRI-Dataset#3]
Hello,

Could you please add the direction parameters for each raw data file to the existing JSON files provided with the dataset? I noticed that some data has incorrect directions during visualization, but it seems that the original data does not include the direction parameters.

Thank you!

**Comment by LMMMEng** [comment]
Hello, thank you for your advice, we will update the direction information soon.
