### ISSUE TITLE
Problem of the OneDrive url

### ISSUE THREAD

**Issue by kenchan0226** [LMMMEng/LLD-MMRI-Dataset#4]
Hi, thanks for the excellent work. 
I tried download the data from the onedrive url: https://reurl.cc/6v362y, after I login my onedrive account, it says that my account can't be found in the connecthkuhk-my.sharepoint.com directory. It seems that your file can only downloaded by the onedrive accounts of HKU. Could you please help fix this issue? Thanks!

**Comment by LMMMEng** [comment]
Hi, thanks for your interest. Please check if this link can work?

**Comment by LMMMEng** [comment]
Thank you for your interest! Could you please check if this link is working? (https://connecthkuhk-my.sharepoint.com/:f:/g/personal/loumeng_connect_hku_hk/Ev1W6Br6uLNFnqaZxyfe7jcBh_V_DLapq4qKv-HyZ0qGnA?e=sblTlk).

**Comment by kenchan0226** [comment]
This link works! Thanks for your help!
