### ISSUE TITLE
weights of model

### ISSUE THREAD

**Issue by zhsn99** [LMMMEng/LLD-MMRI-Dataset#5]
Hi,
I was wondering if I can have access to the weights of your trained model I found link which is not working anymore.
thank you so much.

**Comment by LMMMEng** [comment]
Hi, I've verified the model link and it's working correctly: 'https://github.com/LMMMEng/LLD-MMRI2023/releases/download/release-v1/best_f1_checkpoint-216.pth.tar'. The usage of the weights can be found here: 'https://github.com/LMMMEng/LLD-MMRI2023/tree/main/main'.

**Comment by LMMMEng** [comment]
Please feel free to reopen this issue if you have further questions.
